apiVersion: v1
kind: Service
metadata:
  name: {{ include "captureorder.fullname" . }}
  labels:
    app: {{ include "captureorder.name" . }}
    chart: {{ include "captureorder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: {{ include "captureorder.name" . }}
    release: {{ .Release.Name }}
 
  